### ISSUE TITLE
Error !!

### ISSUE THREAD

**Issue by danzee1** [n0kovo/DomainDouche#2]
Showing this error while running the command:

"UNRECOGNIZED REPLY! TRY WITH FRESH COOKIE."

Tried it multiple times with new cookies but still same response...

**Comment by n0kovo** [comment]
Are you using both the cookies and the user-agent from the same browser/session?

**Comment by danzee1** [comment]
Yes... using same browser's user agent & cookies ,, i carefully read the instructions.

**Comment by n0kovo** [comment]
I am not able to reproduce. What does your final command look like?

**Comment by n0kovo** [comment]
Closing due to lack of communication
